version: '3.1'

services:

#    network_mode: "hostchat"

  tgbot:
    container_name: in_support
    build: .
    volumes:
      - .:/src
    command: python app.py
    restart: always
    network_mode: "bridge"

    env_file:
      - ".env"
